#!name=NodeSeek Daily Check-in
#!desc=NodeSeek forum automatic daily check-in
#!author=Sliverkiss
#!homepage=https://github.com/Sliverkiss
#!icon=https://raw.githubusercontent.com/Sliverkiss/QuantumultX/main/icon/nodeseek.png

[Script]
nodeseek_cookie = type=http-request, pattern=^https:\/\/www\.nodeseek\.com, script-path=https://gist.githubusercontent.com/Sliverkiss/2b5acc2c4960dd06618c6912302c2c7f/raw/nodeseek.js, requires-body=false

nodeseek_checkin = type=cron, cronexp="0 9 * * *", script-path=https://gist.githubusercontent.com/Sliverkiss/2b5acc2c4960dd06618c6912302c2c7f/raw/nodeseek.js

[MITM]
hostname = %APPEND% www.nodeseek.com
